
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/webserver
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  # Spring Swagger
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace