
# spring.main.allow-circular-references to true
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/webserver
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  # Spring Swagger
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  main:
    allow-circular-references: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace